version: "3.7"
services:
  wordpress:
    image: wordpress
    ports:
      - 5000:80
    volumes:
      - ./lambda:/var/www/html/wp-content/plugins/lambda
  sql:
    image: mariadb
    environment:
      MYSQL_DATABASE: "wordpress"
      MYSQL_ROOT_PASSWORD: "secret123456"
